name: Deploy Site

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Trigger deploy
      run: curl -X POST "${{ secrets.DEPLOY_WEBHOOK_URL }}?token=${{ secrets.PLOI_DEPLOY_TOKEN }}"
