name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  tests:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        node-version: [14]

    services:
      redis:
        image: redis:6-alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache dependencies
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-npm-

    - name: Install dependencies
      run: npm install
      
    - name: Install server dependencies
      run: cd ./tests/server && npm install && cd -
      
    - name: Run test server
      run: node ./tests/server/index.js &
    
    - name: Wait for server startup
      run: sleep 1

    - name: Run the tests with coverage
      run: npm run test -- --coverage --coverageReporters json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json

